_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 3
            "12": 0.20.1
            "13": windows-amd64
dataset:
    value: ZINC
framework:
    value: optuna
test_param:
    value: 123
