_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 9
                - 35
                - 41
                - 77
                - 103
            "2":
                - 1
                - 9
                - 35
                - 41
                - 77
                - 103
            "3":
                - 13
                - 16
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
                - 3
            "10":
                - 20
            "12": 0.20.1
            "13": windows-amd64
add_random_walk_pe:
    value: false
add_self_loops:
    value: true
batch_size:
    value: 64
betas:
    value:
        - 0.9
        - 0.999
dropout:
    value: 0.06974693032602092
edge_features:
    value: 4
explained_variance_ratio:
    value: 0.8528818292014123
global_dropout:
    value: 0
gnn_config:
    value:
        dropout_rate: 0.06974693032602092
        hidden_dim: 128
        layer_name: GCN
        num_layers: 5
        use_layer_norm: false
        use_residual: false
gnn_type:
    value: GCN
gradient_clip_algorithm:
    value: norm
gradient_clip_val:
    value: 1
hidden_dim:
    value: 128
huber_delta:
    value: 1
label_smoothing:
    value: 0
learning_rate:
    value: 0.012604664585649461
log_embeddings:
    value: false
log_predictions:
    value: false
loss:
    value: mae
lr:
    value: 0.012604664585649461
lr_scheduler:
    value: none
momentum:
    value: null
monitor_metric:
    value: val_mae
node_features:
    value: 28
normalize_features:
    value: true
num_layers:
    value: 5
optimizer:
    value: adam
pipeline_config:
    value: custom
pooling_config:
    value:
        pooling_type: set2set
        processing_steps: 1
pooling_type:
    value: set2set
processing_steps:
    value: 1
regressor_activation:
    value: swish
regressor_config:
    value:
        activation: swish
        hidden_dims:
            - 64
            - 16
        mlp_dropout: 0.12938999080000846
        regressor_type: residual_mlp
regressor_dropout:
    value: 0.12938999080000846
regressor_hidden_dims:
    value:
        - 64
        - 16
regressor_type:
    value: residual_mlp
scheduler:
    value: none
target_mean:
    value: null
target_std:
    value: null
use_augmentation:
    value: false
use_batch_norm:
    value: false
use_dim_reduction:
    value: false
use_layer_norm:
    value: false
use_residual:
    value: false
warmup_epochs:
    value: 0
weight_decay:
    value: 0.0048696409415209
